version: "3.7"
services:
  react_app:
    environment:
      - ENV=${ENV}
      - PORT=${PORT}
    container_name: luminuszz-wep-app
    restart: always
    build:
      context: .
      dockerfile: "dockerfile"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next



