version: "3.7"
services:
  react_app:
    environment:
      - PORT=${PORT}
      - DOCKER_FILE_ENV=${DOCKER_FILE_ENV}
    container_name: luminuszz-wep-app
    restart: always
    build:
      context: .
      dockerfile: "./docker/${DOCKER_FILE_ENV}/dockerfile"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app
      - /app/node_modules



